server:
  port: 9901


spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    data: classpath:data-h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true